name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  publish-npm-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run publish-packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
